title: [Eduardo Soler´s Portfolio of Cybersecurity Projects.]
description: Some of my Cybersecurity projects to showcase my skills. Enjoy employers :D
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
